apiVersion: v1
kind: Service
metadata:
  name: kotsadm-nginx-proxy
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443
  selector:
    app: kotsadm-nginx-proxy
